### ISSUE TITLE
Thanks your great work, could you please release the dataset?

### ISSUE THREAD

**Issue by zetaodu** [AlvinWen428/spatial-relation-benchmark#1]

**Comment by AlvinWen428** [comment]
Thanks for your interest. I will release it as soon as possible.

**Comment by zetaodu** [comment]
> Thanks for your interest. I will release it as soon as possible.

Hello, can you provide an approximate time

**Comment by AlvinWen428** [comment]
Hello, I have released the codebase and dataset. Thanks for your patience.
